Repository xeol-io/xeol, pull requests merged in 2023-10, with the labels that each got.

#187 add metadata in goreleaser snapshot
  .goreleaser.yaml
Labels: size/XS

#196 Increase xeol.io timeout + add warning
  internal/xeolio/request.go
Labels: size/XS

#198 make `normalizeSemver` handle 4 component versions
  xeol/search/purl.go
  xeol/search/purl_test.go
Labels: size/S

#205 upgrade oras-credentials-go to 0.3.1
  go.mod
  go.sum
Labels: size/S

#204 SLSA attestations for releases
  .github/workflows/release.yaml
  .goreleaser.yaml
  README.md
  test/install/1_download_snapshot_asset_test.sh
  test/install/3_install_asset_test.sh
Labels: size/L

#179 Change README header
  README.md
Labels: size/S

#209 docs: fix the SLSA provenance file name
  README.md
Labels: size/XS

#211 ci: run the Release workflow by the push tag event
  .github/workflows/release.yaml
Labels: size/M
