Repository xeol-io/xeol, pull requests merged in 2023-02, with the labels that each got.

#14 Add lookahead cli option
  cmd/root.go
  go.mod
  go.sum
  internal/config/application.go
  test/integration/match_by_image_test.go
  xeol/lib.go
  xeol/matcher/matchers.go
  xeol/matcher/packages/matcher.go
  xeol/matcher/packages/matcher_test.go
  xeol/presenter/table/presenter.go
  xeol/presenter/table/presenter_test.go
  xeol/search/purl.go
Labels: size/L

#15 Include product name in results
  xeol/db/v1/store/model/cycle.go
  xeol/db/v1/store/store.go
  xeol/eol/cycle.go
Labels: size/XS

#23 Add docker base image with shell
  Dockerfile
Labels: size/XS

#26 [bugfix] Make METHOD work with binary finding
  .github/workflows/release.yaml
  .github/workflows/validations.yaml
  Makefile
  test/integration/db_mock_test.go
  test/integration/match_by_image_test.go
  test/integration/test-fixtures/image-python-3.4/Dockerfile
  test/integration/test-fixtures/image-redis-5/Dockerfile
  xeol/pkg/package.go
  xeol/presenter/table/presenter.go
Labels: size/L

#27 Add installation tests
  .github/workflows/validations.yaml
  install.sh
  test/install/0_search_for_asset_test.sh
  test/install/Makefile
  test/install/github_test.sh
  test/install/test-fixtures/github-api-xeol-v0.1.0-release.json
  test/install/test-fixtures/github-api-xeol-v0.2.2-release.json
  test/install/test-fixtures/xeol_0.1.0-SNAPSHOT-d461f63_checksums.txt
  test/install/test-fixtures/xeol_0.1.0_checksums.txt
  test/install/test-fixtures/xeol_0.2.2_checksums.txt
Labels: size/L

#28 Handle boolean EOL from endoflife.date
  xeol/db/v1/eol.go
  xeol/db/v1/store/model/cycle.go
  xeol/eol/cycle.go
  xeol/presenter/json/test-fixtures/snapshot/TestJsonDirsPresenter.golden
  xeol/presenter/json/test-fixtures/snapshot/TestJsonImgsPresenter.golden
  xeol/presenter/models/cycle.go
  xeol/presenter/models/models_helpers.go
  xeol/presenter/table/presenter.go
  xeol/presenter/table/presenter_test.go
  xeol/presenter/table/test-fixtures/snapshot/TestTablePresenter.golden
  xeol/search/purl.go
Labels: size/M

#29 :memo: doc(README) : Easier copy/past for install (& sudo)
  README.md
Labels: size/XS
