Repository xeol-io/xeol, pull requests merged in 2024-01, with the labels that each got.

#264 Update README.md
  README.md
Labels: size/S

#265 Update README.md
  README.md
Labels: size/XS

#274 correct warn message in ByDistroCpe
  xeol/search/purl.go
Labels: size/XS

#272 handle tilde in version strings
  xeol/search/purl.go
  xeol/search/purl_test.go
Labels: size/S

#273 update noqcks/syft version
  go.mod
  go.sum
Labels: size/XS

#277 don't fail when git repo can't be parsed
  cmd/xeol/cli/options/project_name.go
Labels: size/XS

#278 allow passing of commit hash on the cli
  cmd/xeol/cli/options/xeol.go
  cmd/xeol/internal/types/commit.go
  cmd/xeol/internal/types/commit_test.go
  cmd/xeol/internal/types/projectname.go
  cmd/xeol/internal/types/projectname_test.go
Labels: size/L

#279 Revert "allow passing of commit hash on the cli"
  cmd/xeol/cli/options/xeol.go
  cmd/xeol/internal/types/commit.go
  cmd/xeol/internal/types/commit_test.go
  cmd/xeol/internal/types/projectname.go
  cmd/xeol/internal/types/projectname_test.go
Labels: size/L
