Repository xeol-io/xeol, pull requests merged in 2025-02, with the labels that each got.

#480 Add support for purl constraints in Cycle checks. Change log level default to Error. Bump default lookahead to 1y
  .gitignore
  cmd/xeol/cli/cli.go
  cmd/xeol/cli/options/xeol.go
  go.mod
  go.sum
  test/integration/test-fixtures/npm-angular-14/package.json
  xeol/search/purl.go
Labels: size/M

#500 use .Debug instead of .Warn for match failures
  xeol/matcher/matchers.go
Labels: size/XS

#503 feat(MaxAllowedBuiltAge): increase built age to 90d
  cmd/xeol/cli/options/database.go
Labels: size/XS

#505 feat(db): Add support for a sample when testing via homebrew #504
  xeol/db/curator.go
Labels: size/S
